# -*- coding: utf-8 -*-
"""SAE.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zaQnGBw3CeLfUXPiah2y5km0Aaa8Y6Jj
"""

pip install mysql-connector-python

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# %matplotlib inline

import mysql.connector as MC

try:
  conn = MC.connect(host = 'sql.freedb.tech', database = 'freedb_SAE-S4', user ='freedb_TonyG', password = '8wrGdDJqKu@5Ug5')
  cursor = conn.cursor()

  req = 'SELECT Etablissement, COUNT(*) FROM `info perso` as i, alimentation as a WHERE i.ID = a.ID and a.`Mange Matin` = "oui" GROUP BY Etablissement'
  cursor.execute(req)

  data = {}
  for i in cursor.fetchall():
    data[i[0]] = i[1] 

except MC.Error as err:
  print(err)


fig, ax = plt.subplots()
ax.pie(data.values(), autopct = '%1.2f%%', shadow =True)
ax.legend(title = "Nombres d'étudiants qui mangent le matin en fonction de leurs niveaux", title_fontsize=(14), loc='center', bbox_to_anchor=(0.5, 1.1),  labels=data.keys())

plt.show()

try:
  conn = MC.connect(host = 'sql.freedb.tech', database = 'freedb_SAE-S4', user ='freedb_TonyG', password = '8wrGdDJqKu@5Ug5')
  cursor = conn.cursor()



except MC.Error as err:
  print(err)


fig, (ax1, ax2) = plt.subplots(nrows=1, ncols=2)
req1 = 'SELECT Entree, COUNT(*) FROM `info perso` as i, aliments as a WHERE i.ID = a.ID and i.Etablissement = "Lycee" GROUP BY Entree ORDER BY 1'
cursor.execute(req1)

data = {}
for i in cursor.fetchall():
  data[i[0]] = i[1] 

ax1.pie(data.values(), autopct = '%1.2f%%', shadow =True)
ax1.legend(title = "Types d'entree les plus choisies parmi les collégiens", title_fontsize=(14), loc='center', bbox_to_anchor=(0.5, 1.3),  labels=data.keys())

req2 = 'SELECT Entree, COUNT(*) FROM `info perso` as i, aliments as a WHERE i.ID = a.ID and i.Etablissement = "College" GROUP BY Entree ORDER BY 1'
cursor.execute(req2)

data = {}
for i in cursor.fetchall():
  data[i[0]] = i[1] 

ax2.pie(data.values(), autopct = '%1.2f%%', shadow =True)
ax2.legend(title = "Types d'entree les plus choisies parmi les lycéens", title_fontsize=(14), loc='center', bbox_to_anchor=(0.5, 1.3),  labels=data.keys())

plt.subplots_adjust(right=2.1, wspace=0.2, top=0.85)

plt.show()

try:
  conn = MC.connect(host = 'sql.freedb.tech', database = 'freedb_SAE-S4', user ='freedb_TonyG', password = '8wrGdDJqKu@5Ug5')
  cursor = conn.cursor()



except MC.Error as err:
  print(err)


fig, (ax1, ax2) = plt.subplots(nrows=1, ncols=2)
req1 = 'SELECT Poisson, COUNT(*) FROM `info perso` as i, aliments as a WHERE i.ID = a.ID and i.Etablissement = "Lycee" GROUP BY Poisson ORDER BY 1'
cursor.execute(req1)

data = {}
for i in cursor.fetchall():
  data[i[0]] = i[1] 

ax1.pie(data.values(), autopct = '%1.2f%%', shadow =True)
ax1.legend(title = "Types de poisson les plus choisies parmi les collégiens", title_fontsize=(14), loc='center', bbox_to_anchor=(0.5, 1.3),  labels=data.keys())

req2 = 'SELECT Poisson, COUNT(*) FROM `info perso` as i, aliments as a WHERE i.ID = a.ID and i.Etablissement = "College" GROUP BY Poisson ORDER BY 1'
cursor.execute(req2)

data = {}
for i in cursor.fetchall():
  data[i[0]] = i[1] 

ax2.pie(data.values(), autopct = '%1.2f%%', shadow =True)
ax2.legend(title = "Types de poisson les plus choisies parmi les lycéens", title_fontsize=(14), loc='center', bbox_to_anchor=(0.5, 1.3),  labels=data.keys())

plt.subplots_adjust(right=2, wspace=0.2, top=0.85)

plt.show()

try:
  conn = MC.connect(host = 'sql.freedb.tech', database = 'freedb_SAE-S4', user ='freedb_TonyG', password = '8wrGdDJqKu@5Ug5')
  cursor = conn.cursor()



except MC.Error as err:
  print(err)


fig, (ax1, ax2) = plt.subplots(nrows=1, ncols=2, figsize=(7, 6))
req1 = 'SELECT Viande, COUNT(*) FROM `info perso` as i, aliments as a WHERE i.ID = a.ID and i.Etablissement = "Lycee" GROUP BY Viande ORDER BY 1'
cursor.execute(req1)

data = {}
for i in cursor.fetchall():
  data[i[0]] = i[1] 

ax1.pie(data.values(), autopct = '%1.2f%%', shadow =True)
ax1.legend(title = "Types de viande les plus choisies parmi les collégiens", title_fontsize=(14), loc='center', bbox_to_anchor=(0.5, 1.3),  labels=data.keys())

req2 = 'SELECT Viande, COUNT(*) FROM `info perso` as i, aliments as a WHERE i.ID = a.ID and i.Etablissement = "College" GROUP BY Viande ORDER BY 1'
cursor.execute(req2)

data = {}
for i in cursor.fetchall():
  data[i[0]] = i[1] 

ax2.pie(data.values(), autopct = '%1.2f%%', shadow =True)
ax2.legend(title = "Types de viande les plus choisies parmi les lycéens", title_fontsize=(14), loc='center', bbox_to_anchor=(0.5, 1.3),  labels=data.keys())

plt.subplots_adjust(right=2, wspace=0.2, top=0.85)

plt.show()

try:
  conn = MC.connect(host = 'sql.freedb.tech', database = 'freedb_SAE-S4', user ='freedb_TonyG', password = '8wrGdDJqKu@5Ug5')
  cursor = conn.cursor()



except MC.Error as err:
  print(err)


fig, (ax1, ax2) = plt.subplots(nrows=1, ncols=2, figsize=(8,8))
req1 = 'SELECT Compose, COUNT(*) FROM `info perso` as i, aliments as a WHERE i.ID = a.ID and i.Etablissement = "Lycee" GROUP BY Compose ORDER BY 1'
cursor.execute(req1)

data = {}
for i in cursor.fetchall():
  data[i[0]] = i[1] 

ax1.pie(data.values(), autopct = '%1.2f%%', shadow =True)
ax1.legend(title = "Types de compose les plus choisies parmi les collégiens", title_fontsize=(14), loc='center', bbox_to_anchor=(0.5, 1.2),  labels=data.keys())

req2 = 'SELECT Compose, COUNT(*) FROM `info perso` as i, aliments as a WHERE i.ID = a.ID and i.Etablissement = "College" GROUP BY Compose ORDER BY 1'
cursor.execute(req2)

data = {}
for i in cursor.fetchall():
  data[i[0]] = i[1] 

ax2.pie(data.values(), autopct = '%1.2f%%', shadow =True)
ax2.legend(title = "Types de compose les plus choisies parmi les lycéens", title_fontsize=(14), loc='center', bbox_to_anchor=(0.5, 1.2),  labels=data.keys())

plt.subplots_adjust(right=2, wspace=0.2, top=0.85)
plt.show()



